config/routes.rb
RemoteGpsTracker::Application.routes.draw do
  resources :coordinates

end

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
  validates :latitude,  numericality: { greater_than_or_equal_to: -90,  less_than_or_equal_to: 90 }
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :altitude,  numericality: { less_than: 1000000 }
  validates :gps_timestamp, presence: true

  belongs_to :location

  before_create :find_location

  US_CENTRAL = 'US/Central'

  def self.find_by_date(date, timezone = US_CENTRAL)
    Coordinate.where("(gps_timestamp::timestamptz at time zone ?)::date = ?", timezone, date)
  end

  def self.total_km_travelled
    ActiveRecord::Base.connection.execute("
      WITH ROWS AS
      (
        SELECT *, row_number() over (order by created_at) as rn
        FROM coordinates
      )
      SELECT sum(geodistance_km(c1.latitude, c1.longitude, c2.latitude, c2.longitude)) as km
      FROM rows c1
      JOIN rows c2 on c1.rn = c2.rn - 1;
    ").first["km"].to_f
  end

  def self.total_miles_travelled
    km_to_miles(total_km_travelled)
  end

  def self.average_kmh
    ActiveRecord::Base.connection.execute("
      WITH ROWS AS
      (
        SELECT *, row_number() over (order by created_at) as rn
        FROM coordinates
      )
      SELECT sum(geodistance_km(c1.latitude, c1.longitude, c2.latitude, c2.longitude)) /
             (select extract(epoch from max(c2.gps_timestamp) - min(c1.gps_timestamp))/3600) as kmh
      FROM rows c1
      JOIN rows c2 on c1.rn = c2.rn - 1;
    ").first["kmh"].to_f
  end

  def self.average_mph
    km_to_miles(average_kmh)
  end

  # Measures the delay between when a gps data point is initially collected and
  # subsequently stored in the datebase
  def self.average_transmission_delay
    Coordinate.average("date_part('epoch', created_at) - date_part('epoch', gps_timestamp)").to_f
  end

  # Central Time Zone
  def self.unique_dates(timezone = US_CENTRAL)
    Coordinate.select("(gps_timestamp::timestamptz at time zone '#{timezone}')::date as date").distinct.map(&:date).sort.reverse
  end

  private

  def self.km_to_miles(km)
    km * 0.621371
  end

  def find_location
    self.location_id  = Location.select(:id)
                                .order("geodistance_km(#{self.latitude.to_f}, #{self.longitude.to_f}, latitude, longitude)")
                                .limit(1).first.id
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  self.inheritance_column = nil
  has_many :coordinates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController

  def index
    @unique_dates = Coordinate.unique_dates
    coordinates = (params[:date] ? Coordinate.find_by_date(params[:date]) : Coordinate.all)
    @coordinate_array = coordinates.map { |coordinate| [coordinate.latitude, coordinate.longitude] }
    @latest_coordinate = CoordinatePresenter.new(Coordinate.eager_load(:location).last)
  end

  def create
    latitude, longitude, altitude, date, time = params[:Body].split(",")
    gps_timestamp = DateTime.strptime(date + time, "%d%m%y%H%M%S%L")

    Coordinate.create(
      latitude: latitude.to_f, longitude: longitude.to_f,
      altitude: altitude.to_f, gps_timestamp: gps_timestamp
    )

    render nothing: true, status: 200
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinates_helper.rb
module CoordinatesHelper
end

app/views/coordinates/index.html.erb
<div class="container-fluid" style="height:100%">
  <div class="row-fluid" style="height:100%">
    <div class="span9" style="height:100%" id="map-canvas"></div>
    <div class="span3" style="height:100%" id="map-info"</div>
      <h2>Stats</h2>
      <strong>Current location:</strong>
      <p><%= @latest_coordinate.formatted_location %></p>
      <strong>Altitude:</strong>
      <p><%= @latest_coordinate.altitude.to_s + " meters" %></p>
      <strong>Timestamp:</strong>
      <p><%= @latest_coordinate.formatted_gps_timestamp %></p>
      </br>
      <% @unique_dates.each do |date| %>
        <p><%= link_to date, coordinates_path(date: date) %></p>
      <% end %>
    </div>
  </div>
</div>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
<script>
  map = new Map(<%= @coordinate_array.to_json %>);
  map.initialize();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RemoteGpsTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>